import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#6c2389",
        "on-background": "#1a1c1b",
        "on-tertiary-fixed-variant": "#474648",
        "surface-variant": "#e2e3e1",
        "surface-container-low": "#f4f4f2",
        "primary": "#843ca1",
        "surface-container-high": "#e8e8e6",
        "error": "#ba1a1a",
        "on-primary-container": "#fffbff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "secondary-fixed": "#f2dcf1",
        "surface": "#f9f9f7",
        "primary-fixed-dim": "#edb1ff",
        "surface-container": "#eeeeec",
        "tertiary": "#5c5c5d",
        "surface-dim": "#dadad8",
        "on-secondary-container": "#6e5d6f",
        "outline": "#807381",
        "secondary": "#69596b",
        "secondary-fixed-dim": "#d5c0d5",
        "tertiary-fixed-dim": "#c8c6c7",
        "inverse-primary": "#edb1ff",
        "primary-container": "#9f55bc",
        "primary-fixed": "#f9d8ff",
        "on-error": "#ffffff",
        "tertiary-fixed": "#e4e2e3",
        "inverse-on-surface": "#f1f1ef",
        "surface-tint": "#873ea3",
        "on-primary-fixed": "#320046",
        "outline-variant": "#d1c2d1",
        "on-tertiary-fixed": "#1b1b1c",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f9f9f7",
        "inverse-surface": "#2f3130",
        "on-surface": "#1a1c1b",
        "on-secondary-fixed": "#241726",
        "on-tertiary-container": "#fffcfd",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#514253",
        "surface-container-highest": "#e2e3e1",
        "on-surface-variant": "#4e4350",
        "tertiary-container": "#757475",
        "secondary-container": "#efd9ee",
        "surface-container-lowest": "#ffffff",
        "background": "#f9f9f7",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "stack-gap": "24px",
        "section-padding": "120px",
        "container-max": "720px",
        gutter: "32px",
      },
      fontFamily: {
        "headline-lg": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "headline-md": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "720px",
      },
    },
  },
  plugins: [],
};

export default config;
